{
  "expected_result": {
    "response": {
      "message": "An error occurred while processing the request: Task with id = a8098c1a-f86e-11da-bd1a-001124440000 belongs to another user",
      "code": "BAD_REQUEST"
    },
    "database_data": [],
    "status_code": 400
  },
  "initial_data": {
    "request_body": {
      "task": {
        "id": "a8098c1a-f86e-11da-bd1a-001124440000",
        "user_id": 789,
        "name": "Some task name",
        "description": "Some task description",
        "status": "completed",
        "created_at": "2025-04-19T10:00:00+00:00",
        "updated_at": "2025-04-20T10:00:00+00:00",
        "completed_at": "2025-04-21T10:00:00+00:00"
      }
    }
  }
}
